{
  "作者": "",
  "站名": "AVTop10",
  "头部集合": "User-Agent$Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36#authority$avtop10.com#referer$https://avtop10.com/",
  "分类": "最新影片&热门影片&高清影片&日本AV&欧美AV&动漫AV&中文字幕AV&无码AV&偷拍自拍&制服诱惑&人妻熟女&巨乳美乳&制服诱惑&学生校园&SM调教&网络红人&3P群交&乱伦家庭&强奸迷奸&性爱技巧&自慰诱惑",
  "分类值": "1&2&3&4&5&6&7&8&9&10&11&12&13&14&15&16&17&18&19&20&21",
  "分类url": "https://avtop10.com/api.php/provide/vod/?ac=list&ac=detail&t={cateId}&pg={catePg}",
  "数组二次截取": "list\":[&&]",
  "数组": "{&&}",
  "图片": "vod_pic\"*\"&&\"",
  "标题": "vod_name\"*\"&&\"",
  "副标题": "vod_remarks\"*\"&&\"",
  "链接": "https://avtop10.com/api.php/provide/vod/?ac=list&ac=detail&ids=+vod_id\":&&,",
  "搜索url": "https://avtop10.com/api.php/provide/vod/?ac=detail&wd={wd}",
  "搜索模式": "1",
  "搜索二次截取": "list\":[&&]",
  "搜索数组": "{&&}",
  "搜索图片": "vod_pic\"*\"&&\"",
  "搜索标题": "vod_name\"*\"&&\"",
  "搜索副标题": "vod_remarks\"*\"&&\"",
  "搜索链接": "https://avtop10.com/api.php/provide/vod/?ac=list&ac=detail&ids=+vod_id\":&&,",
  "影片类型": "vod_class\"*\"&&\"",
  "导演": "vod_director\"*\"&&\"",
  "主演": "vod_actor\"*\"&&\"",
  "简介": "vod_content\"*\"&&\"",
  "线路二次截取": "\"list\":[&&]",
  "线路数组": "\"vod_play_from\":&&,",
  "线路标题": "\"&&\"",
  "播放数组": "vod_play_url\":&&,[替换:\">>链表题#$>>题链#\\#>>链表表题]",
  "播放二次截取": "",
  "播放列表": "表&&表",
  "播放标题": "题&&题",
  "播放链接": "链&&链+?sku=OWY3ZDA4ZjVjYzY3YmRhYjM5NTUwYzEyZWRjNjUyZWM1NjQ2ZGRjYTVhMGVkM2Nh&p=1&sign=9a69d1563936ead3677623722660c4d9",
  "播放请求头": "User-Agent$Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36#Referer$https://avtop10.com/#Cookie$PHPSESSID=t9a0fl2ngh4t175j3995v2669d",
  "嗅探词": ".m3u8#.mp4#video_mp4#feiyunNB.mp4#.mp4#cdn.123pan.cn#huoshanvod.com"
}