{"urls":[
{"name":"t0821AA","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t0821AA.json"},
{"name":"t000","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t000.json"},
{"name":"t0820","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t0820.json"},
{"name":"t243_tvbox","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t243_tvbox.json"},
{"name":"t0821A","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t0821A.json"},
{"name":"t48_m","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t48_m.json"},
{"name":"t929_m","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t929_m.json"},
{"name":"ttvbox1","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/ttvbox1.json"},
{"name":"t589_m","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t589_m.json"},
{"name":"t0821","url":"https://raw.githubusercontent.com/sqspot/tac/main/測試倉/t0821.json"}
]}
