{
"spider":"./f0223.jar",
"wallpaper":"https://api.btstu.cn/sjbz/api.php","logo":"http://rihou.cc:567/1.gif",
"lives":[{"name":"外置测试","type":0,"url":"https://gh-proxy.com/raw.githubusercontent.com/sln654360/itv/refs/heads/main/itv.txt","ua":"okhttp/3.15","epg":"https://iptv.crestekk.cn/epgphp/?ch={name}&date={date}","logo":"https://live.fanmingming.cn/tv/{name}.png","catchup":{"type":"append","source":"?livemode=4&starttime=${(b)yyyyMMdd'T'HHmm}00.00Z&endtime=${(e)yyyyMMdd'T'HHmm}00.00Z"}}],
"headers":[{"host":"gslbserv.itv.cmvideo.cn","header":{"User-Agent":"okhttp/3.12.13"}}],
"proxy":["raw.githubusercontent.com"],
"hosts":["cache.ott.ystenlive.itv.cmvideo.cn=39.135.132.221","cache.ott.bestlive.itv.cmvideo.cn=39.135.132.221","cache.ott.wasulive.itv.cmvideo.cn=39.135.132.221","cache.ott.fifalive.itv.cmvideo.cn=39.135.132.221","cache.ott.hnbblive.itv.cmvideo.cn=39.135.132.221"],
"ads":["static-mozai.4gtv.tv"],
"sites":[
{"key":"drpy","name":"🔥豆瓣(有評分 )　２０２５👉財運如🪱,連綿不斷🌻一定要平平安安呦✅","type":3,"api":"./lib/drpy2.min.js","ext":"./js/豆瓣.js"},
//{"key":"csp_Bili短剧","name":"B站短剧","api":"csp_Bili","type":3,"searchable":1,"quickSearch":1,"filterable":1,"jar":"./XYQH.jar","ext":"./js/Bili短剧.json"},
//{"key":"瓜子短劇","name":"瓜子短劇","type":3,"api":"csp_Gz360","searchable":1,"quickSearch":0,"filterable":1,"order_num":0,"jar":"./nzk.jar","changeable":0},
{"key":"csp_Bili短剧","name":"B站短剧2","api":"csp_Bili","type":3,"searchable":1,"quickSearch":1,"filterable":1,"ext":"./js/Bili短剧.json"},
{"key":"瓜子短劇","name":"瓜子短劇2","type":3,"api":"csp_Gz360","searchable":1,"quickSearch":0,"filterable":1,"order_num":0,"changeable":0},
{"key":"cpsx阿里","name":"旺旺短劇","type":3,"playerType":2,"changeable":0,"api":"csp_Wwys","ext":"https://www.wwgz.cn/#"},
{"key":"cspxSuBaiBai","name":"SuBaiBai","type":3,"api":"csp_SuBaiBai","playerType":2,"jar":"./nzk.jar","ext":"https://subaibai.com/"},
{"key":"cspxJPYY","name":"csp_JPYY","type":3,"searchable":1,"changeable":1,"api":"csp_Jpyy","playerType":2,"filterable":1,"jar":"./nzk.jar","ext":""}
],
"parses":[
{"name":"T并发","type":0,"url":"https://jx.xmflv.com/?url=","ext":{"header":{"user-agent":"Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/110.0.0.0Safari/537.36Edg/110.0.1587.57"
}
}
},
{"name":"V嗅探","type":3,"url":"Web"
},
{"name":"分享","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url=","User-Agent":"okhttp/3.12.0","ext":{"flag":[
"qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","yk","mgtv","芒果","CL4K","renrenmi","ltnb","bilibili","1905","xigua"
]
}
},
{"name":"TV","url":"http://180.102.25.145:66/api/jsonindex.php/?key=vd4Kpwz3WxUEg16hmf&url=","type":1,"ext":{"flag":[
"qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"
],"header":{"User-Agent":"LuaSocket3.0-rc1"
}
},"header":{"User-Agent":"LuaSocket3.0-rc1"
}
},
{"name":"魔改","url":"https://jx.255tv.tk/api/?key=S6kQHaE1gVEY5KAv8L&url=","type":1,"ext":{"flag":[
"qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"
],"header":{"User-Agent":"LuaSocket3.0-rc1"
}
},"header":{"User-Agent":"LuaSocket3.0-rc1"
}
},
{"name":"交流","url":"https://api.itcxo.cn/api/jsonindex.php/?key=zfFfINCGuFDFqzc24L&url=","type":1,"ext":{"flag":[
"qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"
],"header":{"User-Agent":"LuaSocket3.0-rc1"
}
},"header":{"User-Agent":"LuaSocket3.0-rc1"
}
},
{"name":"QQ","url":"https://jx.bozrc.com:4433/player/?url=","showType":1
},
{"name":"频道","type":0,"url":"https://jx.777jiexi.com/player/?url="
},
{"name":"号码","type":0,"url":"https://jx.bozrc.com:4433/player/?url=","ext":{"header":{"User-Agent":"okhttp/4.1.0"
},"flag":[
"qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"
]
}
},
{"name":"27","type":0,"url":"http://www.miaoys.cc/vip/?url="
},
{"name":"2e","type":0,"url":"https://jx.ppjbk.cn/?url=","ext":{"header":{"User-Agent":"Mozilla/5.0"
}
}
},
{"name":"s4","type":0,"url":"https://jx.jsonplayer.com/player/?url="
},
{"name":"75","url":"https://jx.bozrc.com:4433/player/?url=","type":0,"ext":{"flag":[
"qiyi","imgo","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","leshi","bilibili","哔哩哔哩","哔哩","mgtv","芒果","sohu","xigua","fun","风行"
],"header":{"User-Agent":"Mozilla/5.0"
}
}
},
{"name":"yj","type":0,"url":"https://jx.4kdv.com/?url=","ext":{"header":{"User-Agent":"okhttp/4.1.0"
},"flag":[
"qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","leshi","LS","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"
]
}
},
{"name":"魔","type":3,"url":"Demo"
},
{"name":"改","type":0,"url":"https://www.8090g.cn/?url="
},
{"name":"交","type":0,"url":"https://jx.m3u8.tv/jiexi/?url="
},
{"name":"流","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="
},
{"name":"魔改交流","type":1,"url":"https://jf.hanliu8.cn/api/?key=vGz0SydWbL1XjS3LPX&url=","ext":{"flag":[
"qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","sohu","搜狐","letv","乐视","mgtv","芒果","rx","ltnb","bilibili","1905","xigua"
],"header":{"User-Agent":"okhttp/4.9.1"
}
}
}
],"flags":[
"youku","qq","QQ","iqiyi","qiyi","letv","sohu","tudou","pptv","PPTV","mgtv","ltnb","rx","CL4K","xfyun","wuduzy","wasu","bilibili","renrenmi","xmm","xigua","m1905","funshion","duoduozy","xinluan","ddzy","tgqp","tkqp","XRJX","优酷","芒果","腾讯","爱奇艺","奇艺","哔哩哔哩","哔哩"
],"ijk":[
{"group":"软解码","options":[
{"category":4,"name":"opensles","value":"0"
},
{"category":1,"name":"fflags","value":"fastseek"
},
{"category":4,"name":"framedrop","value":"1"
},
{"category":4,"name":"enable-accurate-seek","value":"0"
},
{"category":4,"name":"start-on-prepared","value":"1"
},
{"category":1,"name":"http-detect-range-support","value":"0"
},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"
},
{"category":2,"name":"skip_loop_filter","value":"48"
},
{"category":4,"name":"reconnect","value":"1"
},
{"category":4,"name":"overlay-format","value":"842225234"
},
{"category":4,"name":"mediacodec","value":"0"
},
{"category":4,"name":"mediacodec-auto-rotate","value":"0"
},
{"category":4,"name":"soundtouch","value":"1"
},
{"category":4,"name":"mediacodec-hevc","value":"0"
},
{"category":1,"name":"dns_cache_timeout","value":"600000000"
}
]
},
{"group":"硬解码","options":[
{"category":4,"name":"opensles","value":"0"
},
{"category":1,"name":"fflags","value":"fastseek"
},
{"category":4,"name":"framedrop","value":"1"
},
{"category":4,"name":"enable-accurate-seek","value":"0"
},
{"category":4,"name":"start-on-prepared","value":"1"
},
{"category":1,"name":"http-detect-range-support","value":"0"
},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"
},
{"category":2,"name":"skip_loop_filter","value":"48"
},
{"category":4,"name":"reconnect","value":"1"
},
{"category":4,"name":"overlay-format","value":"842225234"
},
{"category":4,"name":"mediacodec","value":"1"
},
{"category":4,"name":"mediacodec-auto-rotate","value":"1"
},
{"category":4,"name":"soundtouch","value":"1"
},
{"category":4,"name":"mediacodec-hevc","value":"1"
},
{"category":1,"name":"dns_cache_timeout","value":"600000000"
}
]
}
],"rules":[
{"name":"米来","hosts":[
"zy.behds.cn"
],"regex":[
"#EXTINF"
]
},
{"name":"爱酷","hosts":[
"cdn.json.icu"
],"regex":[
"#EXTINF:1.000000,[\\s\\S]*?#EXT-X-ENDLIST"
]
},
{"name":"量子广告","hosts":[
"vip.lz","hd.lz"
],"regex":[
"#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.433333,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"
]
},
{"name":"非凡广告","hosts":[
"vip.ffzy","hd.ffzy"
],"regex":[
"#EXT-X-DISCONTINUITY\\r*\\n*#EXTINF:6.666667,[\\s\\S]*?#EXT-X-DISCONTINUITY","#EXTINF.*?\\s+.*?1o.*?\\.ts\\s+"
]
},
{"name":"火山嗅探","hosts":[
"huoshan.com"
],"regex":[
"item_id="
]
},
{"name":"抖音嗅探","hosts":[
"douyin.com"
],"regex":[
"is_play_url="
]
}
],"doh":[
			{
				"name":"Google",
				"url":"https://dns.google/dns-query",
				"ips":[
					"8.8.4.4",
					"8.8.8.8"
				]
			},
			{
				"name":"Cloudflare",
				"url":"https://cloudflare-dns.com/dns-query",
				"ips":[
					"1.1.1.1",
					"1.0.0.1",
					"2606:4700:4700::1111",
					"2606:4700:4700::1001"
				]
			},
			{
				"name":"AdGuard",
				"url":"https://dns.adguard.com/dns-query",
				"ips":[
					"94.140.14.140",
					"94.140.14.141"
				]
			},
			{
				"name":"DNSWatch",
				"url":"https://resolver2.dns.watch/dns-query",
				"ips":[
					"84.200.69.80",
					"84.200.70.40"
				]
			},
			{
				"name":"Quad9",
				"url":"https://dns.quad9.net/dns-quer",
				"ips":[
					"9.9.9.9",
					"149.112.112.112"
				]
			}
		],
		"rules":[
			{
				"name":"proxy",
				"hosts":[
					"raw.githubusercontent.com",
					"googlevideo.com",
					"cdn.v82u1l.com",
					"cdn.iz8qkg.com",
					"cdn.kin6c1.com",
					"c.biggggg.com",
					"c.olddddd.com",
					"haiwaikan.com",
					"www.histar.tv",
					"youtube.com",
					"uhibo.com",
					".*boku.*",
					".*nivod.*",
					"*.t4tv.hz.cz",
					".*ulivetv.*"
				]
			},
			{"host":"www.djuu.com","rule":["mp4.djuu.com","m4a"]},{"host":"www.sharenice.net","rule":["huoshan.com","/item/video/"],"filter":[]},
			{"host":"www.sharenice.net","rule":["sovv.qianpailive.com","vid="],"filter":[]},
			{"host":"www.sharenice.net","rule":["douyin.com","/play/"]},
			{"host":"m.ysxs8.vip","rule":["ysting.ysxs8.vip:81","xmcdn.com"],"filter":[]},
			{"host":"hdmoli.com","rule":[".m3u8"]},{"host":"https://api.live.bilibili.com","rule":["bilivideo.com","/index.m3u8"],"filter":["data.bilibili.com/log/web","i0.hdslb.com/bfs/live/"]},
			{"host":"www.agemys.cc","rule":["cdn-tos","obj/tos-cn"]},
			{"host":"www.fun4k.com","rule":["https://hd.ijycnd.com/play","index.m3u8"]},
			{"host":"zjmiao.com","rule":["play.videomiao.vip/API.php","time=","key=","path="]},
			{
				"name":"火山嗅探",
				"hosts":[
					"huoshan.com"
				],
				"regex":[
					"item_id="
				]
			},
			{
				"name":"抖音嗅探",
				"hosts":[
					"douyin.com"
				],
				"regex":[
					"is_play_url="
				]
			},
			{
				"name":"農民嗅探",
				"hosts":[
					"toutiaovod.com"
				],
				"regex":[
					"video/tos/cn"
				]
			},
			{
				"name":"夜市",
				"hosts":[
					"yeslivetv.com"
				],
				"script":[
					"document.getElementsByClassName('vjs-big-play-button')[0].click()"
				]
			},
			{
				"name":"毛驢",
				"hosts":[
					"www.maolvys.com"
				],
				"script":[
					"document.getElementsByClassName('swal-buttonswal-button--confirm')[0].click()"
				]
			},
			{
				"name":"磁力广告",
				"hosts":[
					"magnet"
				],
				"regex":[
					"更多",
					"社區",
					"xuu",
					"最新",
					"直播",
					"更新",
					"社区",
					"有趣",
					"英皇体育",
					"全中文AV在线",
					"澳门皇冠赌场",
					"哥哥快来",
					"美女荷官",
					"裸聊",
					"新片首发",
					"UUE29"
				]
			}
		],"ads":[
"mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"
]
}